services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - nigeria_constitution_network
  


networks:
  nigeria_constitution_network:
    driver: bridge